---
- hosts: webservers
  become: yes
  tasks:
  - name: INSTALAR APACHE
    apt: name=apache2 update_cache=yes state=latest

  - name: HABILITAR MOD_REWRITE
    apache2_module: name=rewrite state=present
    notify:
      - RESTART APACHE2

  - name: APACHE2 ESCUCHA EN PUERTO 9999
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 9999" state=present
    notify:
      - RESTART APACHE2

  - name: APACHE2 VIRTUALHOST EN PUERTO 9999
    lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:9999>" state=present
    notify:
      - RESTART APACHE2

  handlers:
    - name: RESTART APACHE2
      service: name=apache2 state=restarted 