---
- name: CONFIGURAR IPV6 INTERFAZ LOOPBACK 33
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
  - name: CONFIGURAR DIRECCIÓN IPV6
    ios_config:
      parents: "interface Loopback33"
      lines:
      - ipv6 address 3001:ABCD:ABCD:1::1/128
      - ipv6 address FE80::1 link-local

  - name: SHOW IPv6 INTERFACE BRIEF
    ios_command:
      commands:
      - show ipv6 interface brief
    register: output

  - name: GUARDAR OUTPUT EN ./ios_configurations/
    copy:
      content: "{{ output.stdout[0]}}"
      dest: "ios_configurations/IPv6_output_{{ inventory_hostname }}.txt"